### PR TITLE
s4patricia-Create my file

### PR DESCRIPTION
**Pull request by patriciakuissi**
file

# WELCOME TO DEVOPS-EASY-LEARNING S3 PIPELINE  PULL REQUEST SYSTEM 
# Description of the change

> Detailed description here

## Checks and balances

- [x] Tests added and run
- [ ] (External) Interfaces documented
- [ ] Has security implications (describe below)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)

## Related stories, issues and pulls

> Links to Pivotal Tracker stories, JIRA tickets or other pull requests here

## Security considerations

> Describe any security impact this change may have

FROM HERE, LIFE AND  CAREER CHANGE ARE  POSSIBLE

### CODE REVIEW

**Comment by patriciakuissi** [comment]
@ekus-little @s4olga @Collince-T @s4mauro can you approuve?

**Comment by s4mauro** [comment]
Great Job!

**Comment by patriciakuissi** [comment]
sorry just pratique

**Comment by S4erica1** [comment]
good job

**Review by wounjiem — COMMENTED** [review]
Great

**Comment by s4mauro** [comment]
still can't see my pullrequest but i can do everything else

**Comment by S4erica1** [comment]
good

**Comment by Tankouatch** [comment]
Good

**Comment by ekus-little** [comment]
keep up the good well

**Comment by wounjiem** [comment]
great

**Comment by s4julie** [comment]
Good

**Review by wounjiem — COMMENTED** [review]
good job

**Comment by ekus-little** [comment]
continue the good work

**Pull request closed without merging**
